name: example
description: Flutter example for template_package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  template_package:
    path: ../

dev_dependencies:
#  to use localizations you will still need to add this into your app
  flutter_localizations:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" #flutter pub run flutter_launcher_icons:main
  ios: true
  image_path: "assets/images/applogo.jpg"
  image_path_android: "assets/images/applogo.jpg"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
    - assets/images/
    - assets/country_codes.json

