name: template_package
description: >-
  A Set of tools to speed up and keep clean the development of your app.

version: 2.0.0-rc
homepage: https://github.com/spiderion/template_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependency_provider: ^0.0.1
  base_bloc: ^0.0.2
  clean_architecture_components: ^0.1.0-rc.1
  fluttertoast: ^8.0.7
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
