name: template_package
description: >-
  This package will give you a set of tools to speed up and keep clean the development of your app.
  State Management
  Manages the flutter state in a similar but more flexible way then the common flutter bloc
  UseCase interface to implement and organize the application logic of your app
  LoggerDefault to log all your required logs
  Flutter toasts are few of the utilities already incorporated.
  BaseBlocDataState , BaseBlocPrimaryState states and BaseBlocEvent to organize the flow of data between your widget and bloc

version: 1.0.4
homepage: https://github.com/spiderion/template_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependency_provider: ^0.0.1
  base_bloc: ^0.0.2
  clean_architecture_components: ^0.0.2
  fluttertoast: ^8.0.7
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
