name: template_package
description: A template package for flutter apps. that contains a custom_bloc state management and various clean architecture tools to increase the productivity of a flutter app.
publish_to: none
version: 0.0.1
homepage: Template Package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependency_provider:
    git:
      url: https://github.com/spiderion/dependency_provider.git
  base_bloc:
    git:
      url: https://github.com/spiderion/base_bloc.git
  clean_architecture:
    git:
      url: https://github.com/spiderion/clean_architecture.git
  fluttertoast: 8.0.7
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
