name: template_package
description: A template package for flutter apps.
version: 0.0.1
author:
publish_to: none
homepage: Template Package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependency_provider:
    git:
      url: https://github.com/spiderion/dependency_provider.git
  base_bloc:
    git:
      url: https://github.com/spiderion/base_bloc.git
  fluttertoast:
    git:
      url: https://github.com/spiderion/FlutterToast.git
  clean_architecture:
    path: /Users/ionolaru/StudioProjects/clean_architecture
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
