name: template_package
description: A template package for flutter apps.
version: 0.0.1
author:
publish_to: none
homepage: Template Package

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependency_provider:
    path: ../depencency_provider
  base_bloc:
    path: ../base_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
