name: template_packaged
description: A template package for flutter apps.
version: 0.0.1
author:
homepage: Template Package

dependency_provider:
  git:
    url: https://github.com/spiderion/dependency_provider.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
